name: standalone
on:
  workflow_dispatch:
    inputs:
      profile:
        description: EAS build profile (apk/aab)
        required: true
        default: apk
      submit:
        description: EAS submit (no/yes)
        required: true
        default: 'no'
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v1
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Set up EAS
        uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn install
      - name: Start EAS build
        run: eas build --wait --platform=android --profile=${{ github.event.inputs.profile }}
      - name: Restore Google Play credentials
        uses: actions/github-script@v3
        if: github.event.inputs.submit == 'yes'
        env:
          SERVICE_FILE: ${{ secrets.PLAY_SERVICE_FILE }}
        with:
          script: |
            const fs = require('fs')
            fs.writeFileSync('google-services.json', Buffer.from(process.env.SERVICE_FILE, 'base64'));
            console.log('Restored Google Play credentials');
      - name: Submit EAS build
        if: github.event.inputs.submit == 'yes'
        run: eas submit --latest --platform=android --key=google-services.json
